#!/usr/bin/env python
"""Diagnostics analyzer for trade idea desk-cycle replay artifacts.

Reads replay outputs generated by scripts/replay_trade_idea_desk_cycle.py and
prints a desk-style attribution report:

- summary metrics
- portfolio metrics
- performance by bucket
- performance by setup
- performance by ticker
- performance by year
- exit behavior
- holding-period stats
- best/worst realized trades

Research/paper only. No runtime, broker, or live execution code is modified.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import pandas as pd


REALIZED_STATUSES = {"target_hit", "stop_hit", "expired"}
DISPLAY_WIDTH = 170


def _read_csv(path: Path) -> pd.DataFrame:
    if not path.exists() or path.stat().st_size == 0:
        return pd.DataFrame()
    return pd.read_csv(path)


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists() or path.stat().st_size == 0:
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _to_float(value: Any, default: float = 0.0) -> float:
    try:
        if pd.isna(value):
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def _to_numeric(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    out = df.copy()
    for col in cols:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")
    return out


def _realized(trades: pd.DataFrame) -> pd.DataFrame:
    if trades.empty or "status" not in trades.columns:
        return pd.DataFrame()
    realized = trades[trades["status"].astype(str).isin(REALIZED_STATUSES)].copy()
    return _to_numeric(realized, ["realized_pnl", "realized_return_pct", "days_open", "score", "entry_price", "exit_price", "notional"])


def _fmt_pct(value: Any) -> str:
    try:
        v = float(value)
        if math.isnan(v):
            return "n/a"
        return f"{v:.2f}%"
    except (TypeError, ValueError):
        return "n/a"


def _fmt_money(value: Any) -> str:
    try:
        v = float(value)
        if math.isnan(v):
            return "n/a"
        return f"${v:,.2f}"
    except (TypeError, ValueError):
        return "n/a"


def _fmt_num(value: Any, digits: int = 2) -> str:
    try:
        v = float(value)
        if math.isnan(v):
            return "n/a"
        return f"{v:.{digits}f}"
    except (TypeError, ValueError):
        return "n/a"


def _group_stats(realized: pd.DataFrame, group_col: str, min_trades: int = 1) -> pd.DataFrame:
    if realized.empty or group_col not in realized.columns:
        return pd.DataFrame()
    rows: list[dict[str, Any]] = []
    for label, g in realized.groupby(group_col, dropna=False):
        rets = g["realized_return_pct"].dropna()
        pnl = g["realized_pnl"].dropna()
        wins = rets[rets > 0]
        losses = rets[rets <= 0]
        trades = int(len(g))
        if trades < min_trades:
            continue
        rows.append({
            group_col: str(label),
            "trades": trades,
            "win_rate_pct": float((rets > 0).mean() * 100.0) if not rets.empty else 0.0,
            "avg_return_pct": float(rets.mean()) if not rets.empty else 0.0,
            "median_return_pct": float(rets.median()) if not rets.empty else 0.0,
            "avg_win_pct": float(wins.mean()) if not wins.empty else 0.0,
            "avg_loss_pct": float(losses.mean()) if not losses.empty else 0.0,
            "expectancy_pct": float(rets.mean()) if not rets.empty else 0.0,
            "total_pnl": float(pnl.sum()) if not pnl.empty else 0.0,
            "avg_days_open": float(g["days_open"].mean()) if "days_open" in g.columns else 0.0,
            "target_hits": int((g["status"] == "target_hit").sum()) if "status" in g.columns else 0,
            "stop_hits": int((g["status"] == "stop_hit").sum()) if "status" in g.columns else 0,
            "expired": int((g["status"] == "expired").sum()) if "status" in g.columns else 0,
        })
    out = pd.DataFrame(rows)
    if out.empty:
        return out
    return out.sort_values(["total_pnl", "expectancy_pct"], ascending=[False, False])


def _year_stats(realized: pd.DataFrame) -> pd.DataFrame:
    if realized.empty or "exit_date" not in realized.columns:
        return pd.DataFrame()
    df = realized.copy()
    df["year"] = pd.to_datetime(df["exit_date"], errors="coerce").dt.year
    return _group_stats(df.dropna(subset=["year"]), "year")


def _exit_stats(realized: pd.DataFrame) -> pd.DataFrame:
    if realized.empty:
        return pd.DataFrame()
    rows = []
    total = len(realized)
    for status, g in realized.groupby("status"):
        rows.append({
            "exit": status,
            "trades": int(len(g)),
            "share_pct": float(len(g) / total * 100.0) if total else 0.0,
            "avg_return_pct": float(g["realized_return_pct"].mean()),
            "median_return_pct": float(g["realized_return_pct"].median()),
            "total_pnl": float(g["realized_pnl"].sum()),
            "avg_days_open": float(g["days_open"].mean()) if "days_open" in g.columns else 0.0,
        })
    return pd.DataFrame(rows).sort_values("trades", ascending=False)


def _daily_stats(daily: pd.DataFrame) -> dict[str, Any]:
    if daily.empty:
        return {}
    d = _to_numeric(daily, ["equity", "open", "pending", "reserved_exposure_pct", "open_exposure_pct", "tickets", "raw_signals"])
    out: dict[str, Any] = {}
    if "equity" in d.columns and not d["equity"].dropna().empty:
        eq = d["equity"].dropna()
        out["min_equity"] = float(eq.min())
        out["max_equity"] = float(eq.max())
        out["final_equity"] = float(eq.iloc[-1])
        dd = eq / eq.cummax() - 1.0
        out["max_drawdown_pct"] = float(dd.min() * 100.0)
    for col in ["open", "pending", "reserved_exposure_pct", "open_exposure_pct", "tickets", "raw_signals"]:
        if col in d.columns and not d[col].dropna().empty:
            out[f"avg_{col}"] = float(d[col].mean())
            out[f"max_{col}"] = float(d[col].max())
    return out


def _print_portfolio_metrics(summary: dict[str, Any]) -> None:
    print("-" * DISPLAY_WIDTH)
    print("  PORTFOLIO METRICS")
    print("-" * DISPLAY_WIDTH)
    print(
        f"  {'CAGR':<18} {_fmt_pct(summary.get('cagr_pct')):>12}   "
        f"{'MaxDD':<18} {_fmt_pct(summary.get('max_drawdown_pct_on_equity')):>12}   "
        f"{'Calmar':<18} {_fmt_num(summary.get('calmar'), 3):>12}"
    )
    print(
        f"  {'Sharpe':<18} {_fmt_num(summary.get('sharpe'), 3):>12}   "
        f"{'Sortino':<18} {_fmt_num(summary.get('sortino'), 3):>12}   "
        f"{'Ann Vol':<18} {_fmt_pct(summary.get('annualized_vol_pct')):>12}"
    )
    print(
        f"  {'Return':<18} {_fmt_pct(summary.get('total_return_pct_on_capital')):>12}   "
        f"{'Positive days':<18} {_fmt_pct(summary.get('positive_day_rate_pct')):>12}   "
        f"{'Best/Worst day':<18} {_fmt_pct(summary.get('best_day_pct')):>12} / {_fmt_pct(summary.get('worst_day_pct')):<12}"
    )
    print(
        f"  {'Years':<18} {_fmt_num(summary.get('years'), 2):>12}   "
        f"{'Final equity':<18} {_fmt_money(summary.get('final_equity')):>12}   "
        f"{'Realized PnL':<18} {_fmt_money(summary.get('total_realized_pnl')):>12}"
    )


def _print_group_table(title: str, df: pd.DataFrame, label_col: str, limit: int) -> None:
    print("-" * DISPLAY_WIDTH)
    print(f"  {title}")
    print("-" * DISPLAY_WIDTH)
    if df.empty:
        print("  No rows.")
        return
    print(f"  {label_col:<28} {'Trades':>7} {'Win%':>8} {'AvgRet':>9} {'MedRet':>9} {'AvgWin':>9} {'AvgLoss':>9} {'Exp':>9} {'PnL':>14} {'Days':>7} {'T/S/E':>11}")
    for _, row in df.head(limit).iterrows():
        tse = f"{int(row.get('target_hits', 0))}/{int(row.get('stop_hits', 0))}/{int(row.get('expired', 0))}"
        print(f"  {str(row.get(label_col)):<28} {int(row.get('trades', 0)):>7} {_fmt_pct(row.get('win_rate_pct')):>8} {_fmt_pct(row.get('avg_return_pct')):>9} {_fmt_pct(row.get('median_return_pct')):>9} {_fmt_pct(row.get('avg_win_pct')):>9} {_fmt_pct(row.get('avg_loss_pct')):>9} {_fmt_pct(row.get('expectancy_pct')):>9} {_fmt_money(row.get('total_pnl')):>14} {_fmt_num(row.get('avg_days_open'), 1):>7} {tse:>11}")


def _print_exit_table(df: pd.DataFrame) -> None:
    print("-" * DISPLAY_WIDTH)
    print("  EXIT BEHAVIOR")
    print("-" * DISPLAY_WIDTH)
    if df.empty:
        print("  No realized exits.")
        return
    print(f"  {'Exit':<14} {'Trades':>7} {'Share':>8} {'AvgRet':>9} {'MedRet':>9} {'PnL':>14} {'Days':>7}")
    for _, row in df.iterrows():
        print(f"  {str(row.get('exit')):<14} {int(row.get('trades', 0)):>7} {_fmt_pct(row.get('share_pct')):>8} {_fmt_pct(row.get('avg_return_pct')):>9} {_fmt_pct(row.get('median_return_pct')):>9} {_fmt_money(row.get('total_pnl')):>14} {_fmt_num(row.get('avg_days_open'), 1):>7}")


def _print_trade_table(title: str, trades: pd.DataFrame, limit: int, ascending: bool) -> None:
    print("-" * DISPLAY_WIDTH)
    print(f"  {title}")
    print("-" * DISPLAY_WIDTH)
    if trades.empty:
        print("  No realized trades.")
        return
    df = trades.sort_values("realized_return_pct", ascending=ascending).head(limit)
    print(f"  {'Ticker':<8} {'Bucket':<24} {'Setup':<27} {'Exit':<11} {'Entry':<11} {'ExitDate':<11} {'Ret%':>9} {'PnL':>13} {'Days':>5} {'Score':>7}")
    for _, row in df.iterrows():
        print(f"  {str(row.get('ticker')):<8} {str(row.get('bucket')):<24} {str(row.get('setup')):<27} {str(row.get('status')):<11} {str(row.get('entry_date')):<11} {str(row.get('exit_date')):<11} {_fmt_pct(row.get('realized_return_pct')):>9} {_fmt_money(row.get('realized_pnl')):>13} {int(_to_float(row.get('days_open'))):>5} {_fmt_num(row.get('score'), 1):>7}")


def _write_reports(out_dir: Path, tables: dict[str, pd.DataFrame], summary: dict[str, Any], daily_stats: dict[str, Any]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, df in tables.items():
        df.to_csv(out_dir / f"{name}.csv", index=False)
    payload = {"summary": summary, "daily_stats": daily_stats}
    (out_dir / "analysis_summary.json").write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Analyze trade idea replay outputs")
    p.add_argument("--replay-dir", default="artifacts/trade_idea_replay")
    p.add_argument("--out-dir", default="artifacts/trade_idea_replay/analysis")
    p.add_argument("--min-trades", type=int, default=5)
    p.add_argument("--top-n", type=int, default=20)
    p.add_argument("--trade-limit", type=int, default=10)
    return p.parse_args()


def main() -> None:
    args = parse_args()
    replay_dir = Path(args.replay_dir)
    trades = _read_csv(replay_dir / "replay_trades.csv")
    daily = _read_csv(replay_dir / "replay_daily.csv")
    events = _read_csv(replay_dir / "replay_events.csv")
    summary = _read_json(replay_dir / "replay_summary.json")
    realized = _realized(trades)

    bucket = _group_stats(realized, "bucket", args.min_trades)
    setup = _group_stats(realized, "setup", args.min_trades)
    ticker = _group_stats(realized, "ticker", args.min_trades)
    year = _year_stats(realized)
    exits = _exit_stats(realized)
    daily_summary = _daily_stats(daily)

    print("=" * DISPLAY_WIDTH)
    print("  TRADE IDEA REPLAY — DIAGNOSTICS")
    print("=" * DISPLAY_WIDTH)
    print(f"  Replay dir          : {replay_dir}")
    print(f"  Total orders        : {summary.get('total_orders', 0)}")
    print(f"  Realized trades     : {summary.get('closed_realized_trades', 0)}")
    print(f"  Cancelled / Reject  : {summary.get('cancelled_orders', 0)} / {summary.get('rejected_orders', 0)}")
    print(f"  Win rate            : {_fmt_pct(summary.get('win_rate_pct', 0.0))}")
    print(f"  Expectancy / trade  : {_fmt_pct(summary.get('expectancy_pct_per_realized_trade', 0.0))}")
    print(f"  Avg open/pending    : {_fmt_num(daily_summary.get('avg_open', 0.0), 2)} / {_fmt_num(daily_summary.get('avg_pending', 0.0), 2)}")

    _print_portfolio_metrics(summary)
    _print_group_table("PERFORMANCE BY BUCKET", bucket, "bucket", args.top_n)
    _print_group_table("PERFORMANCE BY SETUP", setup, "setup", args.top_n)
    _print_group_table("PERFORMANCE BY TICKER", ticker, "ticker", args.top_n)
    _print_group_table("PERFORMANCE BY YEAR", year, "year", args.top_n)
    _print_exit_table(exits)
    _print_trade_table("BEST REALIZED TRADES", realized, args.trade_limit, ascending=False)
    _print_trade_table("WORST REALIZED TRADES", realized, args.trade_limit, ascending=True)
    print("=" * DISPLAY_WIDTH)

    tables = {
        "by_bucket": bucket,
        "by_setup": setup,
        "by_ticker": ticker,
        "by_year": year,
        "by_exit": exits,
        "best_trades": realized.sort_values("realized_return_pct", ascending=False).head(args.trade_limit) if not realized.empty else pd.DataFrame(),
        "worst_trades": realized.sort_values("realized_return_pct", ascending=True).head(args.trade_limit) if not realized.empty else pd.DataFrame(),
    }
    _write_reports(Path(args.out_dir), tables, summary, daily_summary)
    print(f"  Analysis written to: {args.out_dir}")
    print("  Verdict: DIAGNOSTIC ONLY; no broker/runtime execution.\n")


if __name__ == "__main__":
    main()
