#!/usr/bin/env python
"""Crypto Risk Budget v2 — hybrid finalist composition.

Research-only composition script. Consumes sleeve-level equity curves generated by
`scripts/analyze_crypto_finalist_sleeve_attribution.py` and builds hybrid
portfolio equity curves by selecting ecap75 or cap75 behavior sleeve-by-sleeve.

This avoids rerunning slow backtests while testing whether the cap75 advantage is
better applied selectively to 4H sleeves instead of promoted across all sleeves.

No runtime, paper-trading, production allocation, or execution changes are made.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

DEFAULT_INPUT = "artifacts/crypto_risk_budget_v2_finalist_sleeve_attribution/sleeve_equity_curves.csv"
DEFAULT_OUT = "artifacts/crypto_risk_budget_v2_hybrid_finalists"
ECAP75 = "trend_following_v8_ecap75"
CAP75 = "trend_following_v8_cap75"
SLEEVES = ["BTC_1H", "BTC_4H", "ETH_1H", "ETH_4H"]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Compose hybrid crypto finalist portfolios from sleeve equity curves",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--sleeve-equity-curves", default=DEFAULT_INPUT)
    p.add_argument("--capital", type=float, default=100_000.0)
    p.add_argument("--out-dir", default=DEFAULT_OUT)
    return p.parse_args()


def _read_curves(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Missing sleeve equity curves file: {path}")
    df = pd.read_csv(path)
    if df.empty:
        raise ValueError(f"Empty sleeve equity curves file: {path}")
    time_col = df.columns[0]
    df[time_col] = pd.to_datetime(df[time_col], errors="coerce")
    df = df.dropna(subset=[time_col]).set_index(time_col).sort_index()
    if df.empty:
        raise ValueError(f"No valid timestamp rows in {path}")
    return df.apply(pd.to_numeric, errors="coerce")


def _required_col(strategy: str, sleeve: str) -> str:
    return f"{strategy}__{sleeve}"


def _validate_columns(curves: pd.DataFrame) -> None:
    missing = []
    for strategy in [ECAP75, CAP75]:
        for sleeve in SLEEVES:
            col = _required_col(strategy, sleeve)
            if col not in curves.columns:
                missing.append(col)
    if missing:
        raise ValueError(f"Missing required sleeve columns: {missing}")


def _compose(curves: pd.DataFrame, mapping: dict[str, str], capital: float, name: str) -> pd.Series:
    selected = {}
    for sleeve, strategy in mapping.items():
        col = _required_col(strategy, sleeve)
        selected[sleeve] = curves[col].dropna().astype(float)
    aligned = pd.DataFrame(selected).dropna()
    returns = aligned.pct_change().fillna(0.0)
    eq = capital * (1.0 + returns.mean(axis=1)).cumprod()
    eq.name = name
    return eq


def _bars_per_year(index: pd.DatetimeIndex) -> float:
    if len(index) < 3:
        return 365.25
    deltas = index.to_series().diff().dropna().dt.total_seconds()
    if deltas.empty:
        return 365.25
    med = float(deltas.median())
    if med <= 0:
        return 365.25
    return float(365.25 * 24 * 3600 / med)


def _max_time_underwater_days(eq: pd.Series) -> float:
    eq = eq.dropna().astype(float)
    if eq.empty:
        return 0.0
    dd = eq / eq.cummax() - 1.0
    underwater = dd < 0
    max_days = 0.0
    start = None
    for ts, flag in underwater.items():
        if flag and start is None:
            start = ts
        elif not flag and start is not None:
            max_days = max(max_days, (ts - start).total_seconds() / 86400.0)
            start = None
    if start is not None:
        max_days = max(max_days, (eq.index[-1] - start).total_seconds() / 86400.0)
    return float(max_days)


def _perf(eq: pd.Series) -> dict[str, float]:
    eq = eq.dropna().astype(float)
    if len(eq) < 2:
        return {
            "total_return_pct": 0.0,
            "cagr_pct": 0.0,
            "max_drawdown_pct": 0.0,
            "sharpe": 0.0,
            "calmar": 0.0,
            "ann_vol_pct": 0.0,
            "worst_90d_return_pct": 0.0,
            "worst_180d_return_pct": 0.0,
            "time_underwater_pct": 0.0,
            "max_time_underwater_days": 0.0,
        }
    total_return = float(eq.iloc[-1] / eq.iloc[0] - 1.0)
    years = max((eq.index[-1] - eq.index[0]).total_seconds() / (365.25 * 24 * 3600), 1e-9)
    cagr = float((eq.iloc[-1] / eq.iloc[0]) ** (1.0 / years) - 1.0)
    dd = eq / eq.cummax() - 1.0
    max_dd = float(dd.min())
    rets = eq.pct_change().dropna()
    std = float(rets.std(ddof=0)) if len(rets) else 0.0
    bpy = _bars_per_year(eq.index)
    sharpe = float((rets.mean() / std) * math.sqrt(bpy)) if std > 1e-12 else 0.0
    ann_vol = float(std * math.sqrt(bpy)) if std > 0 else 0.0
    calmar = float(cagr / abs(max_dd)) if max_dd < 0 else 0.0
    daily = eq.resample("1D").last().dropna()
    worst_90 = float(daily.pct_change(90).dropna().min()) if len(daily) > 90 else 0.0
    worst_180 = float(daily.pct_change(180).dropna().min()) if len(daily) > 180 else 0.0
    return {
        "total_return_pct": total_return * 100.0,
        "cagr_pct": cagr * 100.0,
        "max_drawdown_pct": max_dd * 100.0,
        "sharpe": sharpe,
        "calmar": calmar,
        "ann_vol_pct": ann_vol * 100.0,
        "worst_90d_return_pct": worst_90 * 100.0,
        "worst_180d_return_pct": worst_180 * 100.0,
        "time_underwater_pct": float((dd < 0).mean() * 100.0),
        "max_time_underwater_days": _max_time_underwater_days(eq),
    }


def _hybrid_definitions() -> dict[str, dict[str, str]]:
    return {
        "full_ecap75_reference": {
            "BTC_1H": ECAP75,
            "BTC_4H": ECAP75,
            "ETH_1H": ECAP75,
            "ETH_4H": ECAP75,
        },
        "full_cap75_reference": {
            "BTC_1H": CAP75,
            "BTC_4H": CAP75,
            "ETH_1H": CAP75,
            "ETH_4H": CAP75,
        },
        "hybrid_4h_cap75_1h_ecap75": {
            "BTC_1H": ECAP75,
            "BTC_4H": CAP75,
            "ETH_1H": ECAP75,
            "ETH_4H": CAP75,
        },
        "hybrid_eth4h_cap75_only": {
            "BTC_1H": ECAP75,
            "BTC_4H": ECAP75,
            "ETH_1H": ECAP75,
            "ETH_4H": CAP75,
        },
        "hybrid_btc4h_cap75_only": {
            "BTC_1H": ECAP75,
            "BTC_4H": CAP75,
            "ETH_1H": ECAP75,
            "ETH_4H": ECAP75,
        },
        "hybrid_all_cap75_except_eth1h": {
            "BTC_1H": CAP75,
            "BTC_4H": CAP75,
            "ETH_1H": ECAP75,
            "ETH_4H": CAP75,
        },
        "hybrid_only_eth1h_ecap75": {
            "BTC_1H": CAP75,
            "BTC_4H": CAP75,
            "ETH_1H": ECAP75,
            "ETH_4H": CAP75,
        },
        "hybrid_only_1h_ecap75_duplicate_check": {
            "BTC_1H": ECAP75,
            "BTC_4H": CAP75,
            "ETH_1H": ECAP75,
            "ETH_4H": CAP75,
        },
    }


def _dedupe_defs(defs: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    seen = set()
    out = {}
    for name, mapping in defs.items():
        key = tuple((sleeve, mapping[sleeve]) for sleeve in SLEEVES)
        if key in seen:
            continue
        seen.add(key)
        out[name] = mapping
    return out


def _format_md_value(value: object, floatfmt: str = ".4f") -> str:
    if isinstance(value, float):
        return format(value, floatfmt)
    if pd.isna(value):
        return ""
    return str(value).replace("|", "\\|").replace("\n", " ")


def _to_markdown_table(df: pd.DataFrame, floatfmt: str = ".4f") -> str:
    if df.empty:
        return "_No rows._"
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |"]
    lines.append("| " + " | ".join(["---"] * len(cols)) + " |")
    for _, row in df.iterrows():
        vals = [_format_md_value(row[c], floatfmt=floatfmt) for c in df.columns]
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines)


def _mapping_text(mapping: dict[str, str]) -> str:
    return ", ".join(f"{sleeve}={mapping[sleeve].replace('trend_following_v8_', '')}" for sleeve in SLEEVES)


def _write_markdown(path: Path, summary: pd.DataFrame, target: pd.DataFrame) -> None:
    display_cols = [
        "portfolio", "total_return_pct", "cagr_pct", "max_drawdown_pct", "sharpe", "calmar", "ann_vol_pct",
        "worst_90d_return_pct", "worst_180d_return_pct", "max_time_underwater_days", "mapping",
    ]
    lines = [
        "# Crypto Risk Budget v2 — Hybrid Finalist Composition",
        "",
        "Research-only composition from finalist sleeve equity curves. No runtime or paper-trading changes approved.",
        "",
        "## Summary",
        "",
        _to_markdown_table(summary[[c for c in display_cols if c in summary.columns]]),
        "",
        "## Target Frontier Candidates",
        "",
        _to_markdown_table(target[[c for c in display_cols if c in target.columns]]) if not target.empty else "_No rows met target filters._",
        "",
        "## Guardrail",
        "",
        "```text",
        "These are synthetic combinations of already-backtested sleeve equity curves.",
        "They are useful for research triage but should be confirmed by a direct hybrid runtime/backtest implementation before promotion.",
        "```",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    curves = _read_curves(Path(args.sleeve_equity_curves))
    _validate_columns(curves)

    defs = _dedupe_defs(_hybrid_definitions())
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    portfolio_curves = {}
    rows = []
    for name, mapping in defs.items():
        eq = _compose(curves, mapping, args.capital, name)
        portfolio_curves[name] = eq
        rows.append({
            "portfolio": name,
            **_perf(eq),
            "mapping": _mapping_text(mapping),
            "BTC_1H_strategy": mapping["BTC_1H"],
            "BTC_4H_strategy": mapping["BTC_4H"],
            "ETH_1H_strategy": mapping["ETH_1H"],
            "ETH_4H_strategy": mapping["ETH_4H"],
        })

    summary = pd.DataFrame(rows)
    target = summary[
        (summary["cagr_pct"] >= 25.0)
        & (summary["max_drawdown_pct"] >= -35.0)
        & (summary["sharpe"] >= 1.0)
        & (summary["calmar"] >= 0.9)
    ].copy()

    summary = summary.sort_values(["calmar", "cagr_pct"], ascending=[False, False])
    target = target.sort_values(["calmar", "cagr_pct"], ascending=[False, False])

    pd.DataFrame(portfolio_curves).sort_index().to_csv(out_dir / "hybrid_equity_curves.csv")
    summary.to_csv(out_dir / "hybrid_summary.csv", index=False)
    target.to_csv(out_dir / "target_frontier_candidates.csv", index=False)

    payload = {
        "research_status": "research_only_hybrid_finalist_composition",
        "input": args.sleeve_equity_curves,
        "capital": args.capital,
        "definitions": defs,
        "artifacts": {
            "hybrid_summary": str(out_dir / "hybrid_summary.csv"),
            "target_frontier_candidates": str(out_dir / "target_frontier_candidates.csv"),
            "hybrid_equity_curves": str(out_dir / "hybrid_equity_curves.csv"),
            "summary_json": str(out_dir / "summary.json"),
            "summary_md": str(out_dir / "summary.md"),
        },
        "decision": {
            "status": "diagnostic_only",
            "not_approved": ["runtime_change", "paper_trading_change", "higher_live_exposure", "leverage", "order_routing_change"],
        },
    }
    (out_dir / "summary.json").write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    _write_markdown(out_dir / "summary.md", summary, target)

    display_cols = [
        "portfolio", "total_return_pct", "cagr_pct", "max_drawdown_pct", "sharpe", "calmar", "ann_vol_pct",
        "worst_90d_return_pct", "worst_180d_return_pct", "max_time_underwater_days", "mapping",
    ]
    with pd.option_context("display.max_columns", None, "display.width", 260, "display.float_format", "{:.4f}".format):
        print("\n=== CRYPTO RISK BUDGET V2 — HYBRID FINALIST COMPOSITION ===")
        print(f"Input: {args.sleeve_equity_curves}")
        print("\nHybrid Summary — ranked by Calmar / CAGR:")
        print(summary[[c for c in display_cols if c in summary.columns]].to_string(index=False))
        print("\nTarget Frontier Candidates:")
        if target.empty:
            print("No rows met target filters.")
        else:
            print(target[[c for c in display_cols if c in target.columns]].to_string(index=False))
    print(f"\nArtifacts saved to: {out_dir}")


if __name__ == "__main__":
    main()
