"""Generate a static script-reference inventory; absence is not deletion evidence."""
from __future__ import annotations
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / 'docs/engineering/SCRIPT_INVENTORY.md'


def inventory(root: Path) -> str:
    scripts = sorted(p for p in (root / 'scripts').iterdir() if p.is_file() and p.suffix in {'.py', '.sh'})
    references = [p for folder in ['research', 'runtime', 'scripts', 'tests', 'docs', 'ops'] for p in (root / folder).rglob('*') if p.is_file() and p.suffix in {'.py', '.sh', '.md'} and p.name != 'SCRIPT_INVENTORY.md']
    texts = {p: p.read_text(encoding='utf-8') for p in references}
    lines = ['# Script reference inventory', '',
             'Generated by `scripts/inventory_entrypoints.py`. References are literal filename',
             'or module-name occurrences, not a complete call graph. Zero references do not',
             'prove a script is unused: external schedules, operator commands and dynamic',
             'imports are outside this scan. No deletion or archive move is authorized by it.', '',
             'Historical scripts remain at their original paths for reproducibility.', '',
             '| Script | Code/test references | Documentation references |',
             '| --- | --- | --- |']
    for script in scripts:
        matches = [p for p, text in texts.items() if p != script and (script.name in text or script.stem in text)]
        code = sum(p.suffix in {'.py', '.sh'} for p in matches)
        docs = sum(p.suffix == '.md' for p in matches)
        lines.append(f'| `scripts/{script.name}` | {code} | {docs} |')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    args.output.write_text(inventory(ROOT), encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
